##===- performamcetests/Makefile ----------------------------------*- Makefile -*-===##

LEVEL = ..

include $(LEVEL)/Makefile.config

DIRS = Expr

include $(LEVEL)/Makefile.common

clean::
	$(Verb) $(RM) -f *Tests
